apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    wordpressUsername: bjung
    existingSecret: wordpress-credentials
    wordpressEmail: bjung@vmware.com
    wordpressFirstName: Berndt
    wordpressLastName: Jung
    wordpressBlogName: Berndt's Blog!
    replicaCount: 2