apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
      interval: 1m
  values:
    valuesFrom:
    - kind: Secret
      name: wordpress
      valuesKey: wp-username
      targetPath: wordpressUsername
    - kind: Secret
      name: wordpress
      valuesKey: wp-password
      targetPath: wordpressPassword
    - kind: Secret
      name: wordpress
      valuesKey: mdb-password
      targetPath: mariadb.auth.rootPassword
    replicaCount: 2